// SPDX-License-Identifier: BUSL-1.1
// Licensed under the Business Source License 1.1 (see LICENSE); Change Date: four years from publication; Change License: Apache-2.0
// Copyright (c) 2026 Empower Agile
import { describe, expect, test } from "vitest";
import { boundedContext } from "../src/bounded-context.js";
import { glossary } from "../src/glossary.js";
import { renderGlossaryMarkdown } from "../src/glossary-markdown-renderer.js";
import { type GlossaryTermInput, glossaryTerm } from "../src/glossary-term.js";
import { synonymAlias } from "../src/synonym-alias.js";

const HEADER =
  "# Domain Glossary\n\nGenerated from `glossary.json` — edit the JSON, then regenerate; do not edit this file.\n";

const TABLE_HEADER =
  "| Term | Status | Definition | Deprecated synonyms | Translations |\n|---|---|---|---|---|\n";

function term(overrides: Partial<GlossaryTermInput> & { term: string; context: string }) {
  return glossaryTerm({
    kind: "noun-phrase",
    status: "harvested",
    firstSeen: "2026-08-13",
    ...overrides,
  });
}

describe("renderGlossaryMarkdown", () => {
  test("renders a curated context as one section per kind", () => {
    const model = glossary(
      1,
      new Map([
        ["billing", boundedContext("billing", ["packages/billing"], "Charging, invoicing, funds")],
      ]),
      [
        term({
          term: "overdraft account",
          context: "billing",
          status: "curated",
          definition: "Account permitted to go below zero.",
          translations: new Map([["es", "cuenta con descubierto"]]),
          synonyms: [synonymAlias("account with overdraft", "legacy v1 API phrasing")],
        }),
        term({ term: "open overdraft account", context: "billing", kind: "verb-phrase" }),
      ],
    );

    expect(renderGlossaryMarkdown(model)).toBe(`${HEADER}
## billing

Charging, invoicing, funds

Packages: \`packages/billing\`

### Noun phrases

${TABLE_HEADER}| overdraft account | curated | Account permitted to go below zero. | account with overdraft — legacy v1 API phrasing | es: cuenta con descubierto |

### Verb phrases

${TABLE_HEADER}| open overdraft account | harvested |  |  |  |
`);
  });

  test("renders the header alone for an empty glossary", () => {
    expect(renderGlossaryMarkdown(glossary(1, new Map(), []))).toBe(HEADER);
  });

  test("renders a context that has neither description nor packages", () => {
    const model = glossary(1, new Map([["billing", boundedContext("billing", [])]]), []);

    expect(renderGlossaryMarkdown(model)).toBe(`${HEADER}\n## billing\n`);
  });

  test("lists several packages inline as code spans", () => {
    const model = glossary(
      1,
      new Map([["billing", boundedContext("billing", ["packages/billing", "packages/invoicing"])]]),
      [],
    );

    expect(renderGlossaryMarkdown(model)).toContain(
      "Packages: `packages/billing`, `packages/invoicing`\n",
    );
  });

  test("orders context sections by name and kind tables by the taxonomy", () => {
    const model = glossary(
      1,
      new Map([
        ["shipping", boundedContext("shipping", [])],
        ["billing", boundedContext("billing", [])],
      ]),
      [
        term({ term: "issue invoice", context: "billing", kind: "verb-phrase" }),
        term({ term: "{count} parcels sent", context: "shipping", kind: "template" }),
        term({ term: "invoice", context: "billing", kind: "word" }),
        term({ term: "overdraft account", context: "billing", kind: "noun-phrase" }),
      ],
    );
    const markdown = renderGlossaryMarkdown(model);
    const sections = [...markdown.matchAll(/^#{2,3} (.+)$/gm)].map((match) => match[1]);

    expect(sections).toStrictEqual([
      "billing",
      "Words",
      "Noun phrases",
      "Verb phrases",
      "shipping",
      "Templates",
    ]);
  });

  test("joins several synonyms and translations within their cells", () => {
    const model = glossary(1, new Map([["billing", boundedContext("billing", [])]]), [
      term({
        term: "invoice",
        context: "billing",
        synonyms: [synonymAlias("bill"), synonymAlias("statement", "pre-2020 wording")],
        translations: new Map([
          ["fr", "facture"],
          ["es", "factura"],
        ]),
      }),
    ]);

    expect(renderGlossaryMarkdown(model)).toContain(
      "| invoice | harvested |  | bill; statement — pre-2020 wording | es: factura; fr: facture |\n",
    );
  });

  test("escapes pipes so a term can never break the table", () => {
    const model = glossary(1, new Map([["billing", boundedContext("billing", [])]]), [
      term({
        term: "a | b",
        context: "billing",
        definition: "splits | here",
        synonyms: [synonymAlias("c | d", "note | with pipe")],
        translations: new Map([["es", "e | f"]]),
      }),
    ]);

    expect(renderGlossaryMarkdown(model)).toContain(
      "| a \\| b | harvested | splits \\| here | c \\| d — note \\| with pipe | es: e \\| f |\n",
    );
  });

  test("collapses newlines in a curated definition into spaces", () => {
    const model = glossary(1, new Map([["billing", boundedContext("billing", [])]]), [
      term({ term: "invoice", context: "billing", definition: "first\nsecond\r\nthird\rfourth" }),
    ]);

    expect(renderGlossaryMarkdown(model)).toContain(
      "| invoice | harvested | first second third fourth |  |  |\n",
    );
  });

  test("escapes a pipe in a context name and a package prefix", () => {
    const model = glossary(
      1,
      new Map([["bil|ling", boundedContext("bil|ling", ["pack|ages"])]]),
      [],
    );
    const markdown = renderGlossaryMarkdown(model);

    expect(markdown).toContain("## bil\\|ling\n");
    expect(markdown).toContain("Packages: `pack\\|ages`\n");
  });

  test("ends the document with exactly one trailing newline", () => {
    const model = glossary(1, new Map([["billing", boundedContext("billing", [])]]), [
      term({ term: "invoice", context: "billing" }),
    ]);
    const markdown = renderGlossaryMarkdown(model);

    expect(markdown.endsWith("|\n")).toBe(true);
    expect(markdown.endsWith("\n\n")).toBe(false);
  });
});
