// SPDX-License-Identifier: BUSL-1.1
// Licensed under the Business Source License 1.1 (see LICENSE); Change Date: four years from publication; Change License: Apache-2.0
// Copyright (c) 2026 Empower Agile
import type { BoundedContext } from "./bounded-context.js";
import type { Glossary } from "./glossary.js";
import type { GlossaryTerm } from "./glossary-term.js";
import { TERM_KINDS, type TermKind } from "./term-kind.js";
import { byKey } from "./text-order.js";

const DOCUMENT_HEADER =
  "# Domain Glossary\n\nGenerated from `glossary.json` — edit the JSON, then regenerate; do not edit this file.\n";

const TABLE_HEADER =
  "| Term | Status | Definition | Deprecated synonyms | Translations |\n|---|---|---|---|---|\n";

const ABBREVIATION_TABLE_HEADER = "| Abbreviation | Expansion |\n|---|---|\n";

const KIND_HEADINGS: Record<TermKind, string> = {
  word: "Words",
  "noun-phrase": "Noun phrases",
  "verb-phrase": "Verb phrases",
  template: "Templates",
};

/**
 * Makes text safe inside a table cell: pipes are escaped, and every newline form collapses to a
 * space. A raw pipe would silently split a row into extra columns, and a raw newline would end the
 * table — both turn one bad definition into a corrupted document.
 */
function cell(text: string): string {
  return text.replaceAll("|", "\\|").replaceAll(/\r\n|[\r\n]/g, " ");
}

function synonymsCell(term: GlossaryTerm): string {
  return term.synonyms
    .map((synonym) =>
      synonym.note === undefined
        ? cell(synonym.alias)
        : `${cell(synonym.alias)} — ${cell(synonym.note)}`,
    )
    .join("; ");
}

function translationsCell(term: GlossaryTerm): string {
  return byKey(term.translations)
    .map(([locale, text]) => `${cell(locale)}: ${cell(text)}`)
    .join("; ");
}

function row(term: GlossaryTerm): string {
  const definition = term.definition === undefined ? "" : cell(term.definition);
  const cells = [
    cell(term.term),
    term.status,
    definition,
    synonymsCell(term),
    translationsCell(term),
  ];
  return `| ${cells.join(" | ")} |\n`;
}

function kindTable(terms: readonly GlossaryTerm[], kind: TermKind): string {
  const ofKind = terms.filter((term) => term.kind === kind);
  if (ofKind.length === 0) return "";
  return `\n### ${KIND_HEADINGS[kind]}\n\n${TABLE_HEADER}${ofKind.map(row).join("")}`;
}

/**
 * The shorthand the project has accepted, above the contexts.
 *
 * INTENT: `glossary.md` is the review surface, and accepting an abbreviation is a vocabulary
 * decision — hiding it in the JSON is how it stops being reviewed. Empty section, no heading.
 */
function abbreviationSection(model: Glossary): string {
  if (model.abbreviations.size === 0) return "";
  const rows = byKey(model.abbreviations)
    .map(([abbreviation, expansion]) => `| \`${cell(abbreviation)}\` | ${cell(expansion)} |\n`)
    .join("");
  return `\n## Abbreviations\n\nAccepted shorthand: these are the project's own words, not names to spell out.\n\n${ABBREVIATION_TABLE_HEADER}${rows}`;
}

function contextSection(model: Glossary, context: BoundedContext): string {
  const terms = model.terms.filter((term) => term.context === context.name);
  const parts = [`\n## ${cell(context.name)}\n`];
  if (context.description !== undefined) parts.push(`\n${context.description}\n`);
  if (context.packages.length > 0) {
    parts.push(`\nPackages: ${context.packages.map((name) => `\`${cell(name)}\``).join(", ")}\n`);
  }
  parts.push(...TERM_KINDS.map((kind) => kindTable(terms, kind)));
  return parts.join("");
}

/**
 * Renders the generated `glossary.md` view of a glossary.
 *
 * INTENT: the Markdown view is the PR-review surface (ADR-011) — one section per context, one
 * table per term kind, definitions, synonyms and translations inline, so a reviewer sees the
 * vocabulary change rather than a JSON diff. It is regenerated on every harvest; the JSON stays
 * the single editable source.
 *
 * @param model the glossary to render.
 * @returns Markdown text ending in a newline. Declared abbreviations come first, then contexts
 * ordered by name with kind tables in taxonomy order; a kind with no terms produces no table, a
 * context with no terms produces only its heading, and no declared shorthand produces no
 * abbreviations section at all.
 * @example
 * ```ts
 * writeFileSync("glossary.md", renderGlossaryMarkdown(model), "utf-8");
 * ```
 */
export function renderGlossaryMarkdown(model: Glossary): string {
  const sections = byKey(model.contexts).map(([, context]) => contextSection(model, context));
  return `${DOCUMENT_HEADER}${abbreviationSection(model)}${sections.join("")}`;
}
