// SPDX-License-Identifier: BUSL-1.1
// Licensed under the Business Source License 1.1 (see LICENSE); Change Date: four years from publication; Change License: Apache-2.0
// Copyright (c) 2026 Empower Agile
import { describe, expect, test } from "vitest";
import { reportFields } from "../../src/feedback/feedback-report.js";
import {
  DOCTOR_REPORT_FIELD,
  rulesRefusing,
  valueFreeViolations,
} from "../../src/feedback/value-free-check.js";
import { REDACTION_MARKER } from "../../src/feedback/value-free-matchers.js";
import { completeReport, DOCTOR_JSON } from "./reports.js";

/**
 * The fixture every feedback test starts from, held against the artifact it stands in for.
 *
 * INTENT: in the Java reference this fixture was hand-written and PARAPHRASED the redaction-proof
 * finding — and the paraphrase, having no `[REDACTED]` literal in it, is why 654 green tests did
 * not notice that the gate refused every doctor report there is. Here the fixture is generated by
 * the real doctor, so it carries the generator's bytes by construction; these tests pin the two
 * properties that generation alone does not guarantee.
 */
describe("the doctor-report fixture stands in for the real artifact", () => {
  test("quotes the redaction marker, which is why the exemption exists at all", () => {
    expect(
      DOCTOR_JSON,
      "if the doctor stops quoting the marker, the field exemption is decorative and this test is" +
        " how anybody finds out",
    ).toContain(REDACTION_MARKER);
  });

  test("names the check whose own vocabulary the marker belongs to", () => {
    expect(DOCTOR_JSON).toContain("trap.redaction-proof");
  });

  test("is refused on its own text, by the one rule the doctor's own wording trips", () => {
    expect(rulesRefusing(DOCTOR_JSON).map((rule) => rule.id)).toEqual(["vf.marker"]);
  });

  test("is filable as the doctor-report FIELD of a real report, which is the whole point", () => {
    expect(valueFreeViolations(reportFields(completeReport()))).toEqual([]);
  });

  test("would refuse the whole report from any other field", () => {
    const misfiled = new Map(reportFields(completeReport()));
    misfiled.set("happened", DOCTOR_JSON);
    misfiled.set(DOCTOR_REPORT_FIELD, "");

    expect(valueFreeViolations(misfiled).map((violation) => violation.field)).toEqual(["happened"]);
  });
});
