// SPDX-License-Identifier: BUSL-1.1
// Licensed under the Business Source License 1.1 (see LICENSE); Change Date: four years from publication; Change License: Apache-2.0
// Copyright (c) 2026 Empower Agile
import { runDoctor } from "../../src/doctor/doctor.js";
import { renderJson } from "../../src/doctor/render.js";
import { type Attachments, attachmentsOf } from "../../src/feedback/feedback-attachments.js";
import { feedbackCategory } from "../../src/feedback/feedback-category.js";
import {
  type FeedbackReport,
  feedbackReport,
  problemNarrative,
} from "../../src/feedback/feedback-report.js";
import { snapshot } from "../fixture.js";

/**
 * One complete, value-free report every feedback test starts from, plus named overrides — shaped
 * after `fixture.ts`'s `snapshot()`, so a case says what is DIFFERENT about it rather than reading
 * as eight arguments.
 *
 * INTENT: {@link DOCTOR_JSON} is GENERATED by the real doctor over a real snapshot, never
 * hand-written. In the Java reference the equivalent helper PARAPHRASED the redaction-proof
 * finding, and the paraphrase had no `[REDACTED]` literal in it — which is why 654 green tests did
 * not notice that the gate refused every doctor report there is. A hand-written stand-in for a
 * generated artifact carries the generator's own bytes or it dodges exactly the defect it exists
 * to expose; generating it is the form of that rule no edit can drift away from.
 *
 * `doctor-report-stand-in.test.ts` asserts the generated bytes really do quote the marker, so the
 * exemption this fixture exercises can never become decorative without a test saying so.
 */

/** The doctor's own JSON report for a project with no proof of redaction — the generator's bytes. */
export const DOCTOR_JSON: string = renderJson(runDoctor(snapshot()));

/** A structural trace in this port's own `.nt` grammar, markers and all. */
export const STRUCTURAL_TRACE = `scenario: Order is placed

- OrderService.placeOrder(customerId, total)
  ~ fork [2]
    - Inventory.reserve(sku) → value
    - Pricing.quote(sku) !! RangeError
`;

/** The attachment set every complete report starts from. */
export function completeAttachments(): Attachments {
  return attachmentsOf(DOCTOR_JSON, STRUCTURAL_TRACE);
}

/** A complete report about a doctor check, with both attachments and nothing the gate refuses. */
export function completeReport(): FeedbackReport {
  return feedbackReport({
    runtime: "typescript",
    category: feedbackCategory("doctor"),
    install: "@narrativetrace/core@0.2.0, @narrativetrace/vitest@0.2.0",
    step: "trap.redaction-proof",
    narrative: problemNarrative(
      "ran the doctor, applied the fix it printed, ran it again",
      "the same check still failed, with the same message",
      "the check to pass once the test asserts the marker",
    ),
    language: "en",
    agent: { product: "example-cli", model: "example-model" },
    attachments: completeAttachments(),
  });
}
