// SPDX-License-Identifier: BUSL-1.1
// Licensed under the Business Source License 1.1 (see LICENSE); Change Date: four years from publication; Change License: Apache-2.0
// Copyright (c) 2026 Empower Agile
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { englishDocPages } from "./snippet-shared.js";
import { DEFAULT_REGISTRY_BASE } from "./verify-publication-registry.js";

// The `llms.txt` "docs vs published" banner (family design note, docs-vs-published-gate
// 2026-09-12, part (a); Python's implementation settled five clarifications this module follows):
// one generated line under the `llms.txt` H1 stating whether these docs and the version actually
// live on npm agree, so a reader (human or agent) never has to guess. Generated by `snippet-sync`
// (network allowed) and verified by `snippet-check` (no network — see that file's own header).
//
// Network cadence at check time: the REPO-version half of the line is always verified — it is
// deterministic, read straight from `packages/core/package.json`, no registry involved. The
// PUBLISHED-version half is verified only opportunistically, when a fresh (<1h) cache already
// exists; check never fails merely because the current run happens to be offline (thin-CI /
// offline-nightly convention) — an expired or absent cache simply skips that half of the check.
//
// **The line also counts `unreleased` since-markers** (owner ruling, 2026-09-12; design note
// docs-vs-published-gate-2026-09-12.md §1.1 item 8 + §5.1): the repo version stays at the last
// *published* number until `--tag` bumps it, so the three shapes above can read as fully in sync
// while `*(since X.Y.Z, unreleased)*` markers still sit on the page describing behaviour npm does
// not ship yet. Whenever that count is greater than zero, each shape appends a clause before its
// closing period — `; N behaviour(s) marked unreleased`, singular for a count of 1. The count is a
// pure, deterministic file scan ({@link countUnreleasedMarkers}: `documentation/*.md` including
// `llms-full.md` + `documentation/llms.txt` + root `README.md`, mirrors excluded via the same
// `englishDocPages` `snippet-check`/`snippet-sync` already use for the snippet-drift check), so it
// is verified on every commit alongside the repo-version half — unlike the published-version
// half, which keeps its fresh-cache-only rule.

/** Where the last successful registry lookup is cached — git-ignored (`.tools-cache/`), next to
 * every other tool-self-managed cache this repo already keeps out of source control. */
export const VERSION_CACHE_PATH = ".tools-cache/llms-version-cache.json";

/** How long a cached lookup is trusted before a rebuild goes back to the registry — long enough
 * that repeated local builds don't hammer npm, short enough that the banner is never far behind
 * a real publish. */
export const CACHE_MAX_AGE_MS = 60 * 60 * 1000;

export interface VersionCacheEntry {
  /** The published version the last successful lookup observed. */
  readonly publishedVersion: string;
  /** `Date.now()` at the moment that lookup succeeded. */
  readonly fetchedAtMs: number;
}

/** Reads the cache; `undefined` for "never populated" or "unreadable" alike — either way the
 * caller falls back to a fresh lookup (sync) or skips the published-version check (check). */
export function readVersionCache(path: string = VERSION_CACHE_PATH): VersionCacheEntry | undefined {
  if (!existsSync(path)) return undefined;
  try {
    const parsed = JSON.parse(readFileSync(path, "utf-8")) as Partial<VersionCacheEntry>;
    if (typeof parsed.publishedVersion !== "string" || typeof parsed.fetchedAtMs !== "number") {
      return undefined;
    }
    return { publishedVersion: parsed.publishedVersion, fetchedAtMs: parsed.fetchedAtMs };
  } catch {
    return undefined;
  }
}

/** Only a *successful* lookup is ever cached — a failed/offline lookup leaves the previous entry
 * (if any) exactly as it was, never overwritten with "no answer". */
export function writeVersionCache(
  entry: VersionCacheEntry,
  path: string = VERSION_CACHE_PATH,
): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(entry, null, 2)}\n`, "utf-8");
}

/** Whether a cached lookup is still within {@link CACHE_MAX_AGE_MS} of `nowMs` — a stale cache is
 * never presented as current; the caller must refresh it (sync) or skip that half of the check. */
export function isCacheFresh(entry: VersionCacheEntry, nowMs: number): boolean {
  return nowMs - entry.fetchedAtMs < CACHE_MAX_AGE_MS;
}

/** The cache entry to use right now, or `undefined` if none exists or it has expired. */
export function freshVersionCache(
  cachePath: string = VERSION_CACHE_PATH,
  nowMs: number = Date.now(),
): VersionCacheEntry | undefined {
  const cached = readVersionCache(cachePath);
  return cached && isCacheFresh(cached, nowMs) ? cached : undefined;
}

/** Injectable so a real fetch never has to run in a test — same "no answer" sentinel every other
 * `verify-publication*` registry caller in this repo already uses: a non-200 status (`0` for a
 * network error/timeout) means "don't know", never a thrown error. */
export type FetchLatestStatus = (url: string) => Promise<{ status: number; body: string }>;

async function defaultFetchLatestStatus(url: string): Promise<{ status: number; body: string }> {
  try {
    const res = await fetch(url);
    return { status: res.status, body: await res.text() };
  } catch {
    return { status: 0, body: "" };
  }
}

/** The `dist-tags.latest` version of `packageName` on the registry, or `undefined` for anything
 * short of a clean 200 with a parseable `version` field — same discipline as
 * `verify-publication-registry.ts`'s `classifyStatus`: no answer is no answer, never a guess. */
export async function fetchLatestPublishedVersion(
  packageName: string,
  registryBase: string = DEFAULT_REGISTRY_BASE,
  fetchLatestStatus: FetchLatestStatus = defaultFetchLatestStatus,
): Promise<string | undefined> {
  const { status, body } = await fetchLatestStatus(`${registryBase}/${packageName}/latest`);
  if (status !== 200) return undefined;
  try {
    const parsed = JSON.parse(body) as { version?: unknown };
    return typeof parsed.version === "string" ? parsed.version : undefined;
  } catch {
    return undefined;
  }
}

export interface ResolvedPublishedVersion {
  readonly publishedVersion: string | undefined;
  /** When that answer was obtained — a fresh cache's original fetch time, or "now" for a lookup
   * just made. `undefined` only alongside `publishedVersion: undefined` (offline, no answer). */
  readonly asOfMs: number | undefined;
}

export interface ResolvePublishedVersionOptions {
  readonly packageName: string;
  readonly nowMs: number;
  readonly cachePath?: string;
  readonly registryBase?: string;
  readonly fetchLatestStatus?: FetchLatestStatus;
}

/**
 * The published version to compare against, for `snippet-sync`: a fresh cache is trusted as-is
 * (no network call at all); a missing/stale cache triggers one real lookup, which — on success —
 * is written back to the cache for the next build. `publishedVersion: undefined` means "no
 * answer, from cache or network alike" — the offline line, never a guess.
 */
export async function resolvePublishedVersion(
  options: ResolvePublishedVersionOptions,
): Promise<ResolvedPublishedVersion> {
  const cached = freshVersionCache(options.cachePath, options.nowMs);
  if (cached) return { publishedVersion: cached.publishedVersion, asOfMs: cached.fetchedAtMs };

  const fetched = await fetchLatestPublishedVersion(
    options.packageName,
    options.registryBase,
    options.fetchLatestStatus,
  );
  if (fetched === undefined) return { publishedVersion: undefined, asOfMs: undefined };
  writeVersionCache({ publishedVersion: fetched, fetchedAtMs: options.nowMs }, options.cachePath);
  return { publishedVersion: fetched, asOfMs: options.nowMs };
}

/**
 * Matches one `*(since X.Y.Z, unreleased)*` marker, whitespace-tolerant across BOTH wrap points a
 * real Markdown hard-wrap can introduce — right after `since` (`*(since\n0.1.3, unreleased)*`) or
 * right after the version's comma (`*(since 0.1.3,\nunreleased)*`). A marker split across a line
 * break that way is invisible to a line-based grep/sed (neither half is then a complete line on
 * its own), so every reader of this shape — this counter, the publish script's marker rewrite, and
 * its stale-marker gate — matches against a file's WHOLE text, never one line at a time (owner
 * ruling, 2026-09-12, closing the same gap Python's port found live in its own docs).
 */
export const UNRELEASED_MARKER_RE = /\*\(since\s+[0-9]+(?:\.[0-9]+)*,\s*unreleased\)\*/g;

/** Every English doc file {@link countUnreleasedMarkers} reads: `documentation/*.md` (top level
 * only — `llms-full.md` included, the es/pt-BR/zh-CN mirror subdirectories excluded, exactly what
 * {@link englishDocPages} already computes for the snippet-drift check) plus
 * `documentation/llms.txt`, plus the root `README.md`. */
function unreleasedMarkerFiles(repoRoot: string): string[] {
  const docs = englishDocPages(join(repoRoot, "documentation"));
  const readme = join(repoRoot, "README.md");
  return existsSync(readme) ? [...docs, readme] : docs;
}

/**
 * How many `unreleased` since-markers sit across the English docs right now — a pure,
 * deterministic file scan (no network, no clock), so `snippet-check` can verify the banner's count
 * clause on every commit, unlike the published-version half.
 */
export function countUnreleasedMarkers(repoRoot = "."): number {
  let total = 0;
  for (const file of unreleasedMarkerFiles(repoRoot)) {
    total += readFileSync(file, "utf-8").match(UNRELEASED_MARKER_RE)?.length ?? 0;
  }
  return total;
}

/** The `; N behaviour(s) marked unreleased` clause {@link renderVersionBannerLine} inserts before
 * the closing period — empty for a count of zero, so the line reads exactly as it did before this
 * feature. */
function unreleasedClause(count: number): string {
  if (count <= 0) return "";
  return `; ${count} ${count === 1 ? "behaviour" : "behaviours"} marked unreleased`;
}

const UNRELEASED_CLAUSE_RE = /; (\d+) behaviours? marked unreleased/;

/** The count an already-rendered banner line's clause currently states, or `0` when it carries
 * none at all — the two are equivalent renderings of "nothing unreleased right now". */
export function extractUnreleasedCount(bannerLine: string): number {
  const match = UNRELEASED_CLAUSE_RE.exec(bannerLine);
  return match ? Number(match[1]) : 0;
}

/**
 * The one generated `llms.txt` banner line (design note's three exact forms): versions equal,
 * versions differ, or no answer at all ("published: unknown offline" — never a guess, never a
 * stale cached value presented as fresh) — each optionally carrying the unreleased-count clause
 * (see module doc) when `unreleasedCount` is greater than zero.
 */
export function renderVersionBannerLine(
  repoVersion: string,
  publishedVersion: string | undefined,
  unreleasedCount = 0,
): string {
  const clause = unreleasedClause(unreleasedCount);
  if (publishedVersion === undefined) {
    return `*(These docs describe ${repoVersion}; published: unknown offline${clause}.)*`;
  }
  if (publishedVersion === repoVersion) {
    return `*(Docs and published both at ${repoVersion}${clause}.)*`;
  }
  return `*(These docs describe ${repoVersion}; published is ${publishedVersion}${clause}.)*`;
}

/**
 * Rewrites just the unreleased-count clause of an ALREADY-RENDERED banner line to match `count`,
 * leaving the repo-/published-version prose and any trailing cache-age comment untouched.
 *
 * INTENT: the publish script's `--tag` transform strips shipped since-markers from the staged
 * snapshot only, and must keep this clause in sync with what survives that rewrite — without
 * re-resolving the published-version half, which it never re-queries at tag time (that half keeps
 * whatever a prior `snippet-sync` last resolved).
 */
export function refreshUnreleasedClauseInBanner(bannerLine: string, count: number): string {
  const core = stripCacheAgeComment(bannerLine);
  const trailingComment = bannerLine.slice(core.length);
  const stripped = core.replace(UNRELEASED_CLAUSE_RE, "");
  const withClause = stripped.replace(/\.\)\*$/, `${unreleasedClause(count)}.)*`);
  return withClause + trailingComment;
}

const AGE_COMMENT = /\s*<!--\s*registry checked ([^>]*?)\s*-->\s*$/;

/** Appends the cache-age annotation as a trailing HTML comment — never part of the visible
 * sentence, so it carries the "as of" fact without becoming prose. Omitted entirely when
 * `asOfMs` is `undefined` (the offline line has nothing to time-stamp). */
export function withCacheAgeComment(bannerLine: string, asOfMs: number | undefined): string {
  if (asOfMs === undefined) return bannerLine;
  return `${bannerLine}<!-- registry checked ${new Date(asOfMs).toISOString()} -->`;
}

/** Strips a trailing cache-age comment, if any — the ONLY thing compared for equality anywhere in
 * this module, so a check run minutes or hours after the sync that wrote the comment never flakes
 * on the clock (design note clarification: the age annotation is a comment, not a claim). */
export function stripCacheAgeComment(line: string): string {
  return line.replace(AGE_COMMENT, "");
}

const BANNER_LINE = /^\*\(.*\)\*/;
// A semver token specifically (not "everything up to the next '.'") — the version itself contains
// dots, so a naive "stop at '.' or ';'" cut would truncate "0.2.2" to "0".
const SEMVER = "\\d+\\.\\d+\\.\\d+(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?";
const REPO_VERSION_IN_BANNER = new RegExp(
  `^\\*\\((?:Docs and published both at|These docs describe) (${SEMVER})[;.]`,
);

/** The repo-version half of an already-rendered banner line — parsed back out of the prose so
 * `snippet-check` can verify it deterministically without re-rendering the whole line (which
 * would require knowing the published half too). `undefined` for anything not banner-shaped. */
export function extractRepoVersion(bannerLine: string): string | undefined {
  return REPO_VERSION_IN_BANNER.exec(stripCacheAgeComment(bannerLine))?.[1];
}

/**
 * Rewrites `llmsTxt`'s banner line in place — the first line under the H1 (`# NarrativeTrace`).
 * A pre-existing banner line (matching {@link BANNER_LINE}, age comment and all) is replaced; a
 * page that has never carried one gets it inserted, with the same one-blank-line spacing the page
 * already uses elsewhere. Never touches anything else on the page.
 *
 * @throws {Error} if `llmsTxt` has no top-level `# ` heading at all — a malformed page, not a
 * silent no-op.
 */
export function applyVersionBanner(llmsTxt: string, bannerLine: string): string {
  const lines = llmsTxt.split("\n");
  const h1 = lines.findIndex((line) => line.startsWith("# "));
  if (h1 === -1)
    throw new Error("llms.txt has no top-level '# ' heading to place the banner under");
  const next = lines[h1 + 1];
  if (next !== undefined && BANNER_LINE.test(next)) {
    lines[h1 + 1] = bannerLine; // replace an existing banner in place
  } else if (next === undefined || next.trim() === "") {
    lines.splice(h1 + 1, 0, bannerLine); // the page's own blank separator already follows
  } else {
    lines.splice(h1 + 1, 0, bannerLine, ""); // heading ran straight into content — add the gap
  }
  return lines.join("\n");
}

/** The current banner line already embedded in `llmsTxt` (age comment and all), or `undefined` if
 * it has none yet. */
export function currentVersionBanner(llmsTxt: string): string | undefined {
  const lines = llmsTxt.split("\n");
  const h1 = lines.findIndex((line) => line.startsWith("# "));
  const next = h1 === -1 ? undefined : lines[h1 + 1];
  return next !== undefined && BANNER_LINE.test(next) ? next : undefined;
}

/**
 * Recomputes {@link countUnreleasedMarkers} against `repoRoot`'s current on-disk state and
 * rewrites `documentation/llms.txt`'s banner clause to match, in place. The single regeneration
 * step both the in-tree settle (`settle-since-markers.ts`) and the publish script's staged
 * `--tag` transform call — extracted here so both share one implementation instead of each
 * shelling out to its own copy. A repo with no `documentation/llms.txt`, or one that has never
 * carried a banner line yet, is a no-op (`undefined`): not every tree or snapshot ships one.
 */
export function refreshBannerCount(repoRoot: string): number | undefined {
  const llmsPath = join(repoRoot, "documentation/llms.txt");
  let text: string;
  try {
    text = readFileSync(llmsPath, "utf-8");
  } catch {
    return undefined;
  }

  const banner = currentVersionBanner(text);
  if (banner === undefined) return undefined;

  const count = countUnreleasedMarkers(repoRoot);
  const updated = refreshUnreleasedClauseInBanner(banner, count);
  if (updated !== banner) {
    writeFileSync(llmsPath, applyVersionBanner(text, updated), "utf-8");
  }
  return count;
}
