// SPDX-License-Identifier: BUSL-1.1
// Licensed under the Business Source License 1.1 (see LICENSE); Change Date: four years from publication; Change License: Apache-2.0
// Copyright (c) 2026 Empower Agile
/**
 * The promotion-matrix renderer (skill-evals-multi-platform-2026-09-13.md: "A
 * promotion-matrix renderer (ledger/promotion.md regenerated from runs.jsonl, checked in-gate
 * like the SKILL.md render)"). Pure functions only — no top-level execution, so this module is
 * safely importable from a test; the CLI (`--check`/`--fix`) lives in promotion-render-cli.ts,
 * mirroring tools/skills-render.ts's own drift-check discipline.
 */
export interface LedgerRow {
  readonly date: string;
  readonly skill: string;
  readonly case: string;
  readonly platform: string;
  readonly model: string;
  readonly trial: number;
  readonly result: "pass" | "fail";
  /** Present only on a harness bug or an agent crash — tells that apart from an ordinary grader fail (`evals/runner.ts`). */
  readonly note?: string;
}

export interface SkillLike {
  readonly canonicalName: string;
}

const PLATFORM_COLUMNS = [
  { key: "claude", header: "Claude" },
  { key: "codex", header: "Codex" },
  { key: "gemini", header: "Gemini" },
] as const;

/** One JSON object per non-blank line, the shape `run.ts`'s `appendLedgerRow` writes. */
export function parseRunsJsonl(content: string): readonly LedgerRow[] {
  return content
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .map((line) => JSON.parse(line) as LedgerRow);
}

function rowsFor(
  runs: readonly LedgerRow[],
  skill: string,
  platform: string,
): readonly LedgerRow[] {
  return runs.filter((row) => row.skill === skill && row.platform === platform);
}

/** skill-evals-multi-platform-2026-09-13.md's promotion states: "one green trigger sample + green happy-path". */
function isApproved(rows: readonly LedgerRow[]): boolean {
  const green = (needle: string) =>
    rows.some((row) => row.case.includes(needle) && row.result === "pass");
  return green("happy-path") && green("trigger");
}

function cellFor(runs: readonly LedgerRow[], skill: string, platform: string): string {
  const rows = rowsFor(runs, skill, platform);
  if (rows.length === 0) return "not yet run";
  if (isApproved(rows)) return "approved";
  const latest = rows[rows.length - 1] as LedgerRow;
  const date = latest.date.slice(0, 10);
  return latest.result === "pass"
    ? `green (${latest.model}, ${date})`
    : `red (${latest.model}, ${date})`;
}

const HEADER = `# Promotion matrix

Skill × platform. A cell turns **approved** after one green trigger sample and one green
happy-path case on that platform (skill-harness-design.md §5); **green (model, date)** marks the
most recent passing trial; **red (model, date)** marks the most recent failing one; **not yet
run** means no trial has landed a row in \`ledger/runs.jsonl\` for that pair yet. An empty or
non-approved cell never blocks the nightly — only the Claude lane's own green gates shipping
(\`evals/README.md\`'s sporadic policy) — but it blocks that skill's promotion to fully-approved
status. A wording or fixture change clears that skill's row; re-approval accrues again from
\`ledger/runs.jsonl\`.

Regenerated by \`tools/promotion-render-cli.ts\` from \`ledger/runs.jsonl\` — never hand-edited;
drift fails \`pnpm run check\` (\`pnpm run promotion-check\`; \`pnpm run promotion-render\` fixes it).
`;

/** Regenerates `ledger/promotion.md`'s full content from the typed skill catalogue and the ledger. */
export function renderPromotionMarkdown(
  skills: readonly SkillLike[],
  runs: readonly LedgerRow[],
): string {
  const columnHeaders = PLATFORM_COLUMNS.map((column) => column.header).join(" | ");
  const header = [
    `| Skill | ${columnHeaders} |`,
    `|---|${PLATFORM_COLUMNS.map(() => "---").join("|")}|`,
  ];
  const rows = skills.map((skill) => {
    const cells = PLATFORM_COLUMNS.map((column) => cellFor(runs, skill.canonicalName, column.key));
    return `| \`${skill.canonicalName}\` | ${cells.join(" | ")} |`;
  });
  return `${HEADER}\n${[...header, ...rows].join("\n")}\n`;
}
